### ISSUE TITLE
Installation fails in Windows 11.

### ISSUE THREAD

**Issue by AmirRezaei** [evanhu1/talk2arxiv#1]
yarn
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
warning Error running install script for optional dependency: "R:\\talk2arxiv\\node_modules\\canvas: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build --update-binary
Arguments:
Directory: R:\\talk2arxiv\\node_modules\\canvas
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.11
node-pre-gyp info using node@21.5.0 | win32 | x64
(node:36248) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v120-win32-unknown-x64.tar.gz
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v120-win32-unknown-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not installable for canvas@2.11.2 and node@21.5.0 (node-v120 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v120-win32-unknown-x64.tar.gz

R:\\talk2arxiv\\node_modules\\canvas>if not defined npm_config_node_gyp (node \"C:\\Users\\itkom\\scoop\\apps\\nodejs\\current\\node_modules\\npm\\bin\\node-gyp-bin\\\\..\\..\\node_modules\\node-gyp\\bin\\node-gyp.js\" clean )  else (node \"\" clean )
gyp info it worked if it ends with ok
gyp info using node-gyp@10.0.1
gyp info using node@21.5.0 | win32 | x64
gyp info ok

R:\\talk2arxiv\\node_modules\\canvas>if not defined npm_config_node_gyp (node \"C:\\Users\\itkom\\scoop\\apps\\nodejs\\current\\node_modules\\npm\\bin\\node-gyp-bin\\\\..\\..\\node_modules\\node-gyp\\bin\\node-gyp.js\" configure --fallback-to-build --update-binary --module=R:\\talk2arxiv\\node_modules\\canvas\\build\\Release\\canvas.node --module_name=canvas --module_path=R:\\talk2arxiv\\node_modules\\canvas\\build\\Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v120 )  else (node \"\" configure --fallback-to-build --update-binary --module=R:\\talk2arxiv\\node_modules\\canvas\\build\\Release\\canvas.node --module_name=canvas --module_path=R:\\talk2arxiv\\node_modules\\canvas\\build\\Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v120 )
gyp info it worked if it ends with ok
gyp info using node-gyp@10.0.1
gyp info using node@21.5.0 | win32 | x64
gyp info find Python using Python version 3.12.1 found at \"C:\\Users\\itkom\\scoop\\apps\\python312\\current\\python.exe\"

gyp info find VS using VS2022 (17.8.34330.188) found at:
gyp info find VS \"C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\\Users\\itkom\\scoop\\apps\\python312\\current\\python.exe
gyp info spawn args [
gyp info spawn args 'C:\\\\Users\\\\itkom\\\\scoop\\\\apps\\\\nodejs\\\\21.5.0\\\\node_modules\\\\npm\\\\node_modules\\\\node-gyp\\\\gyp\\\\gyp_main.py',
gyp info spawn args 'binding.gyp',
gyp info spawn args '-f',
gyp info spawn args 'msvs',
gyp info spawn args '-I',
gyp info spawn args 'R:\\\\talk2arxiv\\\\node_modules\\\\canvas\\\\build\\\\config.gypi',
gyp info spawn args '-I',
gyp info spawn args 'C:\\\\Users\\\\itkom\\\\scoop\\\\apps\\\\nodejs\\\\21.5.0\\\\node_modules\\\\npm\\\\node_modules\\\\node-gyp\\\\addon.gypi',
gyp info spawn args '-I',
gyp info spawn args 'C:\\\\Users\\\\itkom\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\21.5.0\\\\include\\\\node\\\\common.gypi',
gyp info spawn args '-Dlibrary=shared_library',
gyp info spawn args '-Dvisibility=default',
gyp info spawn args '-Dnode_root_dir=C:\\\\Users\\\\itkom\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\21.5.0',
gyp info spawn args '-Dnode_gyp_dir=C:\\\\Users\\\\itkom\\\\scoop\\\\apps\\\\nodejs\\\\21.5.0\\\\node_modules\\\\npm\\\\node_modules\\\\node-gyp',
gyp info spawn args '-Dnode_lib_file=C:\\\\\\\\Users\\\\\\\\itkom\\\\\\\\AppData\\\\\\\\Local\\\\\\\\node-gyp\\\\\\\\Cache\\\\\\\\21.5.0\\\\\\\\<(target_arch)\\\\\\\\node.lib',
gyp info spawn args '-Dmodule_root_dir=R:\\\\talk2arxiv\\\\node_modules\\\\canvas',
gyp info spawn args '-Dnode_engine=v8',
gyp info spawn args '--depth=.',
gyp info spawn args '--no-parallel',
gyp info spawn args '--generator-output',
gyp info spawn args 'R:\\\\talk2arxiv\\\\node_modules\\\\canvas\\\\build',
gyp info spawn args '-Goutput_dir=.'
gyp info spawn args ]
Warning: Missing input files:
C:\\GTK\\bin\\libcairo-2.dll
C:\\GTK\\bin\\libpangowin32-1.0-0.dll
C:\\GTK\\bin\\libintl-8.dll
C:\\GTK\\bin\\libfreetype-6.dll
C:\\GTK\\bin\\libexpat-1.dll
C:\\GTK\\bin\\libfontconfig-1.dll
C:\\GTK\\bin\\libpango-1.0-0.dll
C:\\GTK\\bin\\libpangoft2-1.0-0.dll
C:\\GTK\\bin\\libgmodule-2.0-0.dll
C:\\GTK\\bin\\zlib1.dll
C:\\GTK\\bin\\libpng14-14.dll
C:\\GTK\\bin\\libpangocairo-1.0-0.dll
C:\\GTK\\bin\\libgobject-2.0-0.dll
C:\\GTK\\bin\\libgthread-2.0-0.dll
C:\\GTK\\bin\\libglib-2.0-0.dll
gyp info ok

R:\\talk2arxiv\\node_modules\\canvas>if not defined npm_config_node_gyp (node \"C:\\Users\\itkom\\scoop\\apps\\nodejs\\current\\node_modules\\npm\\bin\\node-gyp-bin\\\\..\\..\\node_modules\\node-gyp\\bin\\node-gyp.js\" build --fallback-to-build --update-binary --module=R:\\talk2arxiv\\node_modules\\canvas\\build\\Release\\canvas.node --module_name=canvas --module_path=R:\\talk2arxiv\\node_modules\\canvas\\build\\Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v120 )  else (node \"\" build --fallback-to-build --update-binary --module=R:\\talk2arxiv\\node_modules\\canvas\\build\\Release\\canvas.node --module_name=canvas --module_path=R:\\talk2arxiv\\node_modules\\canvas\\build\\Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v120 )
gyp info it worked if it ends with ok
gyp info using node-gyp@10.0.1
gyp info using node@21.5.0 | win32 | x64
gyp info spawn C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\MSBuild\\Current\\Bin\\MSBuild.exe
gyp info spawn args [
gyp info spawn args 'build\\\\binding.sln',
gyp info spawn args '/clp:Verbosity=minimal',
gyp info spawn args '/nologo',
gyp info spawn args '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]

  Backend.cc
R:\\talk2arxiv\\node_modules\\canvas\\src\\backend\\Backend.h(3,10): error C1083: Cannot open include file: 'cairo.h': No such file or directory [R:\\talk2arxiv\\node_modules\\canvas\\build\\canvas.vcxproj]
  (compiling source file '../src/backend/Backend.cc')

gyp ERR! build error
gyp ERR! stack Error: `C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\MSBuild\\Current\\Bin\\MSBuild.exe` failed with exit code: 1
gyp ERR! stack at ChildProcess.<anonymous> (C:\\Users\\itkom\\scoop\\apps\\nodejs\\21.5.0\\node_modules\\npm\\node_modules\\node-gyp\\lib\\build.js:209:23)
gyp ERR! stack at ChildProcess.emit (node:events:519:28)
gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:294:12)
gyp ERR! System Windows_NT 10.0.22631
gyp ERR! command \"C:\\\\Users\\\\itkom\\\\scoop\\\\apps\\\\nodejs\\\\current\\\\node.exe\" \"C:\\\\Users\\\\itkom\\\\scoop\\\\apps\\\\nodejs\\\\current\\\\node_modules\\\\npm\\\\node_modules\\\\node-gyp\\\\bin\\\\node-gyp.js\" \"build\" \"--fallback-to-build\" \"--update-binary\" \"--module=R:\\\\talk2arxiv\\\\node_modules\\\\canvas\\\\build\\\\Release\\\\canvas.node\" \"--module_name=canvas\" \"--module_path=R:\\\\talk2arxiv\\\\node_modules\\\\canvas\\\\build\\\\Release\" \"--napi_version=9\" \"--node_abi_napi=napi\" \"--napi_build_version=0\" \"--node_napi_label=node-v120\"
gyp ERR! cwd R:\\talk2arxiv\\node_modules\\canvas
gyp ERR! node -v v21.5.0
gyp ERR! node-gyp -v v10.0.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd build --fallback-to-build --update-binary --module=R:\\talk2arxiv\\node_modules\\canvas\\build\\Release\\canvas.node --module_name=canvas --module_path=R:\\talk2arxiv\\node_modules\\canvas\\build\\Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v120' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (R:\\talk2arxiv\\node_modules\\@mapbox\\node-pre-gyp\\lib\\util\\compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:519:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1105:16)
node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
node-pre-gyp ERR! System Windows_NT 10.0.22631
node-pre-gyp ERR! command \"C:\\\\Users\\\\itkom\\\\scoop\\\\apps\\\\nodejs\\\\current\\\\node.exe\" \"R:\\\\talk2arxiv\\\\node_modules\\\\@mapbox\\\\node-pre-gyp\\\\bin\\\\node-pre-gyp\" \"install\" \"--fallback-to-build\" \"--update-binary\"
node-pre-gyp ERR! cwd R:\\talk2arxiv\\node_modules\\canvas
node-pre-gyp ERR! node -v v21.5.0
node-pre-gyp ERR! node-pre-gyp -v v1.0.11
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd build --fallback-to-build --update-binary --module=R:\\talk2arxiv\\node_modules\\canvas\\build\\Release\\canvas.node --module_name=canvas --module_path=R:\\talk2arxiv\\node_modules\\canvas\\build\\Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v120' (1)"
info This module is OPTIONAL, you can safely ignore this error
Done in 5.86s.
 itkom   talk2arxiv    main ≡   

**Comment by claudioantonio** [comment]
I run it on windows 11 but through wsl.
I just opened a wsl Ubuntu terminal, cloned the repo and did `yarn` plus `yarn run dev`.
It worked.
